-- ADICIONAR COLUNAS FALTANTES NA TABELA BRANDING PARA EVITAR ERROS DE SALVAMENTO
ALTER TABLE branding ADD COLUMN IF NOT EXISTS store_name TEXT;
ALTER TABLE branding ADD COLUMN IF NOT EXISTS tax_id TEXT;
ALTER TABLE branding ADD COLUMN IF NOT EXISTS state_registration TEXT;
ALTER TABLE branding ADD COLUMN IF NOT EXISTS warranty_time TEXT;

-- MIGRAR DADOS DA COLUNA WARRANTY (ANTIGA) PARA WARRANTY_TIME (NOVA)
DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'branding' AND COLUMN_NAME = 'warranty') THEN
        UPDATE branding SET warranty_time = warranty WHERE warranty_time IS NULL;
    END IF;
END $$;

-- GARANTIR QUE STORE_NAME TENHA O VALOR DE BUSINESS_NAME SE ESTIVER VAZIO
UPDATE branding SET store_name = business_name WHERE store_name IS NULL;
